item {
  id: 1
  name: 'cursor'
}
item {
  id: 2
  name: 'disconnect'
}
item {
  id: 3
  name: 'offLinePlay'
}
item {
  id: 4
  name: 'favor'
}
item {
  id: 5
  name: 'deathmatch'
}
item {
  id: 6
  name: 'enemy'
}
